### ISSUE TITLE
Home feed Endpoint

### ISSUE THREAD

**Issue by thatcher-gaming** [mogery/cohost.js#4]
hi!   
i'm trying to implement some of the missing features listed in the readme; it says that getting the home feed is possible, but i can't seem to find the endpoint to fetch from in order to do it. do you still have the url for it?

**Comment by mogery** [comment]
hey
the feed is loaded into the website with server-side rendering, and new posts are delivered via the eventstream. i'm not sure if i ever found an endpoint that lets you just straight up fetch your feed, my main idea was to extract the posts from the SSR'd page.

**Comment by Cyber28** [comment]
Hi!
The HTML returned by `GET /` contains a script tag with with the id `__COHOST_LOADER_STATE__`. This JSON has the dashboard object containing display preferences, 20 recent posts, and the used project. For the screenshot below I used [node-html-parser](https://npmjs.com/package/node-html-parser).
This is definitely a slow solution (requesting a large HTML document and parsing it), but how often would people want to request the feed anyways :^)

![image](https://user-images.githubusercontent.com/33525058/200132850-3f1cab16-56ae-46b4-9a3c-3b43a4fece27.png)

This method also works for searching posts by tag, `GET /rc/tagged/:tag`, which returns all posts without pagination

![image](https://user-images.githubusercontent.com/33525058/200133464-afbba32e-4b00-4cd4-9846-19a42e132a6b.png)

**Comment by thatcher-gaming** [comment]
@Cyber28 that works for me! cheers
